---

- name: Reconfigure gitlab
  ansible.builtin.shell: |
    gitlab-ctl deploy-page up || exit 1
    gitlab-ctl backup-etc || exit 1
    gitlab-ctl start || exit 1
    gitlab-ctl reconfigure > /dev/null 2> /dev/null \
      && echo "Reconfiguration successful! :-)" \
      || echo "Reconfiguration failed! :-("
    if grep -q "letsencrypt\['enable'\] *= *true" /etc/gitlab/gitlab.rb; then
      gitlab-ctl renew-le-certs
    fi
    gitlab-ctl deploy-page down
  notify: Enable gitlab service
  changed_when: true

- name: Enable gitlab service
  ansible.builtin.systemd:
    state: started
    enabled: true
    masked: false
    daemon_reload: true
    name: gitlab-runsvdir
