---

- name: Reconfigure gitlab
  ansible.builtin.shell: |
    gitlab-ctl deploy-page up
    gitlab-ctl backup-etc
    gitlab-ctl start
    gitlab-ctl reconfigure > /dev/null 2> /dev/null && echo "Reconfiguration successful! :-)" || echo "Reconfiguration failed! :-("
    ( cat /etc/gitlab/gitlab.rb | grep "letsencrypt" | sed 's/\ //g' | grep "\['enable'\]=true" > /dev/null 2> /dev/null ) && gitlab-ctl renew-le-certs || true
    gitlab-ctl deploy-page down
  notify: Enable gitlab service

- name: Enable gitlab service
  ansible.builtin.systemd:
    state: started
    enabled: yes
    masked: no
    daemon_reload: yes
    name: gitlab-runsvdir
